---
apiVersion: v1
kind: Namespace
metadata:
  name: lsrouji-workspace
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubuntu-24.04
  namespace: lsrouji-workspace
  labels:
    app: ubuntu-24.04
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ubuntu-24.04
  template:
    metadata:
      labels:
        app: ubuntu-24.04
    spec:
      containers:
        - name: ubuntu-24.04
          image: ubuntu:24.04
      volumes:
        - name: src
          configMap:
            name: config